import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { RunSummary } from "../validation";
import { maskRunSummary } from "./mask";

export interface HtmlReportOptions {
  reportsDir: string;
  maskKeys?: string[];
  previousSummary?: RunSummary;
}

export async function writeHtmlReport(
  summary: RunSummary,
  opts: HtmlReportOptions,
): Promise<string> {
  const masked = maskRunSummary(summary, { maskKeys: opts.maskKeys });
  const outDir = path.join(opts.reportsDir, "html", summary.runId);
  await mkdir(outDir, { recursive: true });
  const outPath = path.join(outDir, "index.html");
  await writeFile(outPath, renderHtml(masked, opts.previousSummary));
  return outPath;
}

export function renderHtml(summary: RunSummary, previous?: RunSummary): string {
  const t = summary.totals;
  const passPct = t.total ? Math.round((t.passed / t.total) * 100) : 0;
  const failPct = t.total ? Math.round((t.failed / t.total) * 100) : 0;
  const skipPct = t.total ? Math.round((t.skipped / t.total) * 100) : 0;

  const diff = previous ? computeDiff(summary, previous) : null;

  const rows = summary.scenarios
    .map((s, i) => renderRow(i, s))
    .join("\n");

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>ai-test report — ${escapeHtml(summary.runId)}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>${CSS}</style>
</head>
<body>
  <header class="hdr">
    <div>
      <h1>${escapeHtml(summary.app ?? "Run")}</h1>
      <div class="sub">
        ${escapeHtml(summary.runId)} ·
        <span class="pill">${escapeHtml(summary.mode)}</span>
        <span class="pill pill-level">level: ${escapeHtml(summary.testLevel ?? "system")}</span>
        · ${escapeHtml(summary.startedAt)} → ${escapeHtml(summary.finishedAt)}
      </div>
    </div>
  </header>

  <section class="kpi">
    ${kpiCard("Total", t.total, "")}
    ${kpiCard("Passed", t.passed, "ok", passPct)}
    ${kpiCard("Failed", t.failed, "ko", failPct)}
    ${kpiCard("Skipped", t.skipped, "sk", skipPct)}
  </section>

  ${diff ? renderDiff(diff) : ""}
  ${renderTechniqueCoverage(summary)}

  <section class="list">
    ${rows || '<p class="muted">No scenarios in this run.</p>'}
  </section>

  <footer class="ftr">
    Generated by ai-test · ${escapeHtml(summary.environment.node ?? "")}
  </footer>
  <script>
    document.querySelectorAll('details').forEach(d => d.addEventListener('toggle', e => {}));
  </script>
</body>
</html>
`;
}

function renderRow(
  i: number,
  s: RunSummary["scenarios"][number],
): string {
  const status = s.validation.status;
  const cls = status === "passed" ? "ok" : "ko";
  const steps = s.result.steps
    .map(
      (st) => `
        <li class="step step-${st.status}">
          <span class="pill ${st.status === "passed" ? "ok" : st.status === "failed" ? "ko" : "sk"}">${escapeHtml(st.status)}</span>
          <span class="step-i">#${st.index}</span>
          <span class="step-d">${escapeHtml(s.scenario.steps[st.index]?.description ?? "")}</span>
          ${st.reason ? `<span class="step-r">${escapeHtml(st.reason)}</span>` : ""}
          ${st.screenshotPath ? `<a class="evi" href="${escapeAttr(relative(st.screenshotPath))}">screenshot</a>` : ""}
        </li>`,
    )
    .join("");
  const evidence = [
    s.result.screenshotPath ? `<a href="${escapeAttr(relative(s.result.screenshotPath))}">final screenshot</a>` : null,
    s.result.tracePath ? `<a href="${escapeAttr(relative(s.result.tracePath))}">trace.zip</a>` : null,
  ]
    .filter(Boolean)
    .join(" · ");

  return `
  <details class="scenario ${cls}" ${status === "failed" ? "open" : ""}>
    <summary>
      <span class="pill ${cls}">${escapeHtml(status)}</span>
      <span class="title">${escapeHtml(s.scenario.title)}</span>
      <span class="meta">${escapeHtml(s.scenario.type)} · ${escapeHtml(s.scenario.priority)} · ${escapeHtml(s.scenario.origin)}</span>
    </summary>
    ${s.validation.failureReason ? `<blockquote class="why">${escapeHtml(s.validation.failureReason)}</blockquote>` : ""}
    <ol class="steps">${steps}</ol>
    ${evidence ? `<div class="evidence">${evidence}</div>` : ""}
    ${s.validation.suggestedDefect ? renderDefect(s.validation.suggestedDefect) : ""}
  </details>`;
}

function renderDefect(d: NonNullable<RunSummary["scenarios"][number]["validation"]["suggestedDefect"]>): string {
  return `
    <section class="defect">
      <h4>Suggested defect (severity: ${escapeHtml(d.severity)})</h4>
      <p>${escapeHtml(d.summary)}</p>
      <ul>${d.stepsToReproduce.map((s) => `<li>${escapeHtml(s)}</li>`).join("")}</ul>
    </section>`;
}

interface DiffOutcome {
  newFailures: string[];
  newlyPassing: string[];
}

function computeDiff(current: RunSummary, previous: RunSummary): DiffOutcome {
  const prev = new Map(previous.scenarios.map((s) => [s.scenario.id, s.validation.status]));
  const newFailures: string[] = [];
  const newlyPassing: string[] = [];
  for (const s of current.scenarios) {
    const prevStatus = prev.get(s.scenario.id);
    if (s.validation.status === "failed" && prevStatus !== "failed") {
      newFailures.push(s.scenario.id);
    }
    if (s.validation.status === "passed" && prevStatus === "failed") {
      newlyPassing.push(s.scenario.id);
    }
  }
  return { newFailures, newlyPassing };
}

function renderDiff(d: DiffOutcome): string {
  return `
  <section class="diff">
    <h2>Regression diff</h2>
    <p>+${d.newFailures.length} new failures · +${d.newlyPassing.length} newly passing</p>
    ${d.newFailures.length ? `<details open><summary>New failures</summary><ul>${d.newFailures.map((id) => `<li>${escapeHtml(id)}</li>`).join("")}</ul></details>` : ""}
    ${d.newlyPassing.length ? `<details><summary>Newly passing</summary><ul>${d.newlyPassing.map((id) => `<li>${escapeHtml(id)}</li>`).join("")}</ul></details>` : ""}
  </section>`;
}

function kpiCard(label: string, n: number, cls: string, pct?: number): string {
  return `
    <div class="card ${cls}">
      <div class="n">${n}</div>
      <div class="l">${label}${pct !== undefined ? ` · ${pct}%` : ""}</div>
    </div>`;
}

function renderTechniqueCoverage(summary: RunSummary): string {
  const coverage = summary.techniqueCoverage ?? [];
  if (coverage.length === 0) return "";
  const rows = coverage
    .map((c) => {
      const pct = c.total ? Math.round((c.passed / c.total) * 100) : 0;
      return `<tr><td><code>${escapeHtml(c.technique)}</code></td><td>${c.total}</td><td>${c.passed}</td><td>${pct}%</td></tr>`;
    })
    .join("");
  return `
  <section class="cov">
    <h2>ISTQB technique coverage</h2>
    <table>
      <thead>
        <tr><th>Technique</th><th>Total</th><th>Passed</th><th>Pass rate</th></tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>
  </section>`;
}

const COV_CSS = `
  .cov{margin:0 24px 12px;background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:12px 16px}
  .cov h2{margin:0 0 8px;font-size:1rem}
  .cov table{width:100%;border-collapse:collapse;font-size:.9rem}
  .cov th, .cov td{text-align:left;padding:4px 6px;border-bottom:1px dashed #e2e8f0}
  .pill-level{margin-left:4px}
  @media (prefers-color-scheme: dark){
    .cov{background:#0f172a;border-color:#1e293b}
  }
`;

const CSS = COV_CSS + `
  *{box-sizing:border-box}
  body{margin:0;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:#f8fafc;color:#0f172a}
  .hdr{padding:16px 24px;background:#fff;border-bottom:1px solid #e2e8f0;display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;z-index:10}
  .hdr h1{margin:0;font-size:1.25rem}
  .sub{color:#64748b;font-size:.85rem;margin-top:4px}
  .kpi{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;padding:16px 24px}
  .card{background:#fff;border:1px solid #e2e8f0;border-radius:10px;padding:14px}
  .card.ok{border-left:4px solid #10b981}
  .card.ko{border-left:4px solid #ef4444}
  .card.sk{border-left:4px solid #94a3b8}
  .card .n{font-size:2rem;font-weight:700}
  .card .l{color:#64748b;font-size:.85rem;margin-top:2px}
  .diff{margin:0 24px 12px;padding:12px 16px;background:#fef9c3;border:1px solid #fde68a;border-radius:10px}
  .diff h2{margin:0 0 6px;font-size:1rem}
  .list{padding:0 24px 24px}
  .scenario{background:#fff;border:1px solid #e2e8f0;border-radius:10px;margin-bottom:10px;padding:8px 14px}
  .scenario.ko{border-left:4px solid #ef4444}
  .scenario.ok{border-left:4px solid #10b981}
  .scenario summary{cursor:pointer;display:flex;align-items:center;gap:10px}
  .scenario .title{font-weight:600}
  .scenario .meta{color:#64748b;font-size:.85rem;margin-left:auto}
  .pill{display:inline-block;font-size:.75rem;padding:2px 8px;border-radius:999px;background:#f1f5f9;color:#475569}
  .pill.ok{background:#dcfce7;color:#166534}
  .pill.ko{background:#fee2e2;color:#991b1b}
  .pill.sk{background:#e2e8f0;color:#475569}
  .why{background:#fff1f2;color:#9f1239;padding:8px 12px;border-radius:8px;margin:8px 0;border-left:3px solid #ef4444}
  .steps{margin:8px 0;padding:0;list-style:none}
  .step{display:flex;gap:8px;align-items:center;padding:4px 0;border-bottom:1px dashed #e2e8f0}
  .step-i{color:#94a3b8;font-variant-numeric:tabular-nums;width:34px}
  .step-d{flex:1}
  .step-r{color:#9f1239;font-size:.85rem}
  .evi{color:#0369a1;text-decoration:none;font-size:.85rem;margin-left:8px}
  .evidence{margin:8px 0;font-size:.85rem}
  .defect{margin:10px 0;padding:8px 12px;border:1px dashed #fda4af;border-radius:8px;background:#fff1f2}
  .defect h4{margin:0 0 4px;font-size:.9rem;color:#9f1239}
  .ftr{padding:16px 24px;color:#64748b;font-size:.8rem;border-top:1px solid #e2e8f0;background:#fff}
  .muted{color:#64748b}
  @media (prefers-color-scheme: dark){
    body{background:#020617;color:#e2e8f0}
    .hdr,.card,.scenario,.ftr{background:#0f172a;border-color:#1e293b}
    .card .l,.sub,.scenario .meta,.muted,.step-i{color:#94a3b8}
    .diff{background:#422006;border-color:#854d0e;color:#fef3c7}
  }
`;

function escapeHtml(s: string | undefined | null): string {
  if (s === undefined || s === null) return "";
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
function escapeAttr(s: string): string {
  return escapeHtml(s);
}
function relative(p: string): string {
  if (p.startsWith("/")) {
    // Strip leading cwd if possible
    const cwd = process.cwd();
    if (p.startsWith(cwd)) return path.relative(process.cwd(), p);
  }
  return p;
}
